lib/william_storck_phx_web/router.ex
defmodule WilliamStorckPhxWeb.Router do
  use WilliamStorckPhxWeb, :router

  alias WilliamStorckPhxWeb.Plugs.{RequireLogin, Authenticate}

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Authenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Must be logged out
  scope "/admin", WilliamStorckPhxWeb.Admin, as: :admin do
    pipe_through [:browser]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  # Must be logged in
  scope "/admin", WilliamStorckPhxWeb.Admin, as: :admin do
    pipe_through [:browser, RequireLogin]

    delete "/login", SessionController, :delete

    get "/", LandingController, :index
    resources "/users", UserController
    resources "/paintings", PaintingController
    resources "/categories", CategoryController
  end

  scope "/", WilliamStorckPhxWeb do
    pipe_through :browser # Use the default browser stack

    get "/", HomeController, :index

    get "/portfolio", PortfolioController, :index

    resources "/categories", CategoryController, only: [:show]

    resources "/paintings", PaintingsController, only: [:show]

    get "/contact", ContactController, :index
    post "/contact", ContactController, :capture_email

    get "/sitemap", SitemapController, :index
    get "/privacy", PrivacyController, :index


    get "/*path", PaintingsController, :index
  end
end

lib/william_storck_phx/painting.ex
defmodule WilliamStorckPhx.Painting do
  use Ecto.Schema

  import Ecto.Changeset

  alias WilliamStorckPhx.{UploadService, SlugGenerator}

  @derive {Phoenix.Param, [:id, :slug]}

  @insert_params [
    :name,
    :category_id,
    :material,
    :painting_height,
    :painting_width,
    :price,
    :status,
    :image_file
  ]
  @insert_required [:name, :material, :painting_height, :painting_width, :status, :image_file]

  @update_params [
    :name,
    :category_id,
    :material,
    :painting_height,
    :painting_width,
    :price,
    :status
  ]

  schema "paintings" do
    field :name, :string
    field :material, :string

    field :painting_height, :integer, virtual: true
    field :painting_width, :integer, virtual: true
    field :height, :integer
    field :width, :integer

    field :price, :integer
    field :status, :string

    field :image_file, :any, virtual: true
    field :src, :string

    field :size, :string
    field :slug

    belongs_to :category, WilliamStorckPhx.Admin.Category

    field :featured, :boolean, default: false

    timestamps()
  end

  @doc false
  def insert_changeset(painting, attrs) do
    painting
    |> cast(attrs, @insert_params)
    |> validate_required(@insert_required)
    |> foreign_key_constraint(:category_id)
    |> upload_painting()
    |> cast(attrs, [:src, :height, :width])
    |> validate_required([:src, :height, :width])
    |> change(image_file: nil)
    |> format_size()
    |> cast(attrs, [:size])
    |> validate_required([:size])
    |> change(%{painting_height: nil, painting_width: nil})
    |> generate_slug()
    |> cast(attrs, [:slug])
    |> validate_required([:slug])
  end

  def update_changeset(painting, attrs) do
    painting
    |> cast(attrs, @update_params)
    |> format_size()
    |> generate_slug()
    |> cast(attrs, [:slug])
  end

  defp upload_painting(%Ecto.Changeset{valid?: true,
  changes: %{name: name, image_file: image_file}} = changeset) do
    with %{src: _src, height: _height, width: _width} = changes <- UploadService.upload_file(
    %{name: name, file: image_file}) do
      change(changeset, changes)
    else
      {:error, msg} ->
        add_error(changeset, :src, "Upload failed: #{msg}")
    end
  end

  defp upload_painting(changeset), do: changeset

  defp format_size(%Ecto.Changeset{valid?: true,
  changes: %{painting_height: height, painting_width: width}} = changeset) do
    change(changeset, size: "#{height}\" x #{width}\"")
  end

  defp format_size(%Ecto.Changeset{valid?: true, changes: %{painting_height: _}} = changeset) do
    add_error(changeset, :painting_width, "Cannot be blank")
  end

  defp format_size(%Ecto.Changeset{valid?: true, changes: %{painting_width: _}} = changeset) do
    add_error(changeset, :painting_height, "Cannot be blank")
  end

  defp format_size(changeset), do: changeset

  defp generate_slug(%Ecto.Changeset{valid?: true,
  changes: %{name: name}} = changeset) when not is_nil(name) do
    change(changeset, slug: SlugGenerator.generate_slug(name))
  end

  defp generate_slug(changeset), do: changeset
end

lib/william_storck_phx_web/controllers/admin/painting_controller.ex
defmodule WilliamStorckPhxWeb.Admin.PaintingController do
  use WilliamStorckPhxWeb, :controller

  alias WilliamStorckPhx.Admin
  alias WilliamStorckPhx.Painting

  def index(conn, %{"category_id" => category_id}) do
    paintings = Admin.list_paintings(category_id)
    categories = Admin.list_categories()
    render(conn, "index.html", paintings: paintings, categories: categories)
  end

  def index(conn, _params) do
    paintings = Admin.list_paintings()
    categories = Admin.list_categories()
    render(conn, "index.html", paintings: paintings, categories: categories)
  end

  def new(conn, _params) do
    changeset = Admin.change_painting(%Painting{})
    categories = Admin.list_categories()
    render(conn, "new.html", changeset: changeset, categories: categories)
  end

  def create(conn, %{"painting" => painting_params}) do
    case Admin.create_painting(painting_params) do
      {:ok, painting} ->
        conn
        |> put_flash(:info, "Painting created successfully.")
        |> redirect(to: Routes.admin_painting_path(conn, :show, painting))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    painting = Admin.get_painting!(id)
    render(conn, "show.html", painting: painting)
  end

  def edit(conn, %{"id" => id}) do
    painting = Admin.get_painting!(id)
    changeset = Admin.change_painting(painting)
    categories = Admin.list_categories()
    render(conn, "edit.html", painting: painting, changeset: changeset, categories: categories)
  end

  def update(conn, %{"id" => id, "painting" => painting_params}) do
    painting = Admin.get_painting!(id)

    case Admin.update_painting(painting, painting_params) do
      {:ok, painting} ->
        conn
        |> put_flash(:info, "Painting updated successfully.")
        |> redirect(to: Routes.admin_painting_path(conn, :show, painting))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", painting: painting, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    painting = Admin.get_painting!(id)
    {:ok, _painting} = Admin.delete_painting(painting)

    conn
    |> put_flash(:info, "Painting deleted successfully.")
    |> redirect(to: Routes.admin_painting_path(conn, :index))
  end
end

lib/william_storck_phx_web/controllers/paintings_controller.ex
defmodule WilliamStorckPhxWeb.PaintingsController do
  use WilliamStorckPhxWeb, :controller
  alias WilliamStorckPhx.{Repo, Painting}
  import Ecto.Query

  def index(conn, _params) do
    query = from p in Painting, order_by: fragment("RANDOM()")
    render conn, "index.html", paintings: Repo.all(query)
  end

  def show(conn, %{"id" => slug}) do
    case Repo.get_by(Painting, slug: slug) do
      nil ->
        index(conn, %{})
      painting ->
        render conn, "show.html", painting: painting
    end
  end
end

lib/william_storck_phx_web/views/admin/painting_view.ex
defmodule WilliamStorckPhxWeb.Admin.PaintingView do
  use WilliamStorckPhxWeb, :view

  def current_height(size) do
    size
    |> String.split()
    |> Enum.at(0)
  end

  def current_width(size) do
    size
    |> String.split()
    |> Enum.reverse()
    |> Enum.at(0)
  end

  def category_options(categories) when is_nil(categories), do: ["Create a category first"]
  def category_options(categories) do
    Enum.map(categories, fn c -> {c.name, c.id} end)
  end
end

lib/william_storck_phx_web/views/paintings_view.ex
defmodule WilliamStorckPhxWeb.PaintingsView do
  use WilliamStorckPhxWeb, :view

  def compute_style(painting) do
    width = compute_aspect_ratio(painting)
            |> estimate_width
    width_style = "width: #{width}px;"
    flex_style  = "flex-grow: #{width};"
    width_style <> flex_style
  end

  def compute_spacer_padding(painting) do
    compute_aspect_ratio(painting)
    |> :math.pow(-1)
    |> Kernel.*(100)
    |> round()
  end

  def compute_aspect_ratio(painting) do
    painting.width / painting.height
  end

  def estimate_width(aspect_ratio) do
    round(aspect_ratio * 240)    # starting height
  end
end

lib/william_storck_phx_web/templates/paintings/_painting_preview.html.eex
<%= if assigns[:painting].height do %>
  <div class="painting-grid-item align-self-center" style="<%= compute_style(assigns[:painting]) %>">
    <a href="<%= Routes.paintings_path(@conn, :show, assigns[:painting].slug) %>" class="grid-image">
      <span class="shade-overlay d-none d-lg-block rounded"></span>
      <img
        src="<%= assigns[:painting].src %>"
        alt="<%= assigns[:painting].name %>"
        class="img-fluid rounded"
      >
    </a>
  </div>
<% end %>

lib/william_storck_phx_web/templates/paintings/index.html.eex
<%= render WilliamStorckPhxWeb.SharedView, "navbar_min.html", assigns %>

<div
  class="d-md-none container-fluid mx-auto mt-3 text-center"
  style="padding-top: 100px;"
>
  <div class="painting-grid d-flex flex-wrap justify-content-between">
    <%= for painting <- @paintings do %>
      <%= render WilliamStorckPhxWeb.PaintingsView,
        "_painting_preview.html", %{painting: painting, conn: @conn} %>
    <% end %>
  </div>
</div>

<div
  class="d-none d-md-block container mx-auto mt-3 text-center"
  style="padding-top: 100px;"
>
  <div class="painting-grid d-flex flex-wrap justify-content-between">
    <%= for painting <- @paintings do %>
      <%= render WilliamStorckPhxWeb.PaintingsView,
        "_painting_preview.html", %{painting: painting, conn: @conn} %>
    <% end %>
  </div>
</div>

<%= render WilliamStorckPhxWeb.SharedView, "footer.html", assigns %>

lib/william_storck_phx_web/templates/paintings/show.html.eex
<div id="painting-page">

  <div class="navbar navbar_light justify-content-end py-0">
    <%= link to: Routes.category_path(@conn, :show, @painting.category_id),
        class: "navbar-brand" do %>
      <p class="small text-muted m-0">
        <i class="fas fa-long-arrow-alt-left"></i>
        Collection
      </p>
    <% end %>

  <div class="d-flex d-lg-none flex-column align-items-center justify-content-center">
    <div class="my-2">
      <img
        src="<%= @painting.src %>"
        alt="@painting.name"
        class="img-fluid"
      >
    </div>

    <div class="mt-3">
      <h1 class="display-5 text-center text-primary">
        <%= @painting.name %>
      </h1>

      <div class="text-center border-top border-secondary mt-2 pt-2">
        <h5 class="display-text text-black">
          <%= @painting.material %>
        </h5>

        <h5 class="display-text text-black">
          <%= @painting.size %>
        </h5>
      </div>
    </div>
  </div>

  </div>

  <div class="d-none d-lg-block container-fluid mt-3">
    <div class="row">
      <div class="col-lg-8 col-xl-9 pr-0">
        <div
          id="painting-image-full"
          class="d-flex align-items-center justify-content-center"
        >
          <img
            src="<%= @painting.src %>"
            alt="@painting.name"
            class="elevation-5"
          >
        </div>
      </div>

      <div class="col-lg-4 col-xl-3 pl-0 pr-5">
        <div class="h-100 d-flex flex-column align-items-end justify-content-center">
          <h1 class="display-5 text-right text-primary mr-2">
            <%= @painting.name %>
          </h1>

          <div class="mr-2 pt-4 pr-3 text-right border-right border-secondary">
            <h5>
              <%= @painting.material %>
            </h5>

            <h5>
              <%= @painting.size %>
            </h5>

            <%= if @painting.status === "available" do %>
              <a
                href="<%= Routes.contact_path(@conn, :index, painting: @painting.name) %>"
                class="text-underline"
              >
                Available
                <%= if @painting.price do %>
                  $<%= @painting.price %>
                <% end %>
              </a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>