lib/william_storck_phx_web/router.ex
defmodule WilliamStorckPhxWeb.Router do
  use WilliamStorckPhxWeb, :router

  alias WilliamStorckPhxWeb.Plugs.{RequireLogin, Authenticate}

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Authenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Must be logged out
  scope "/admin", WilliamStorckPhxWeb.Admin, as: :admin do
    pipe_through [:browser]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  # Must be logged in
  scope "/admin", WilliamStorckPhxWeb.Admin, as: :admin do
    pipe_through [:browser, RequireLogin]

    delete "/login", SessionController, :delete

    get "/", LandingController, :index
    resources "/users", UserController
    resources "/paintings", PaintingController
    resources "/categories", CategoryController
  end

  scope "/", WilliamStorckPhxWeb do
    pipe_through :browser # Use the default browser stack

    get "/", HomeController, :index

    get "/portfolio", PortfolioController, :index

    resources "/categories", CategoryController, only: [:show]

    resources "/paintings", PaintingsController, only: [:show]

    get "/contact", ContactController, :index
    post "/contact", ContactController, :capture_email

    get "/sitemap", SitemapController, :index
    get "/privacy", PrivacyController, :index


    get "/*path", PaintingsController, :index
  end
end

lib/william_storck_phx_web/controllers/sitemap_controller.ex
defmodule WilliamStorckPhxWeb.SitemapController do
  use WilliamStorckPhxWeb, :controller
  alias WilliamStorckPhx.{Repo, Painting}

  def index(conn, _params) do
    render conn, "index.html", paintings: Repo.all(Painting)
  end
end

lib/william_storck_phx_web/views/sitemap_view.ex
defmodule WilliamStorckPhxWeb.SitemapView do
  use WilliamStorckPhxWeb, :view
end

lib/william_storck_phx_web/templates/sitemap/index.html.eex
<div class="bg-beige">
  <%= render WilliamStorckPhxWeb.SharedView, "navbar_min.html", assigns %>

  <div class="container text-left" style="padding-top: 120px; padding-bottom: 80px;">
    <h3 class="display-text text-blue">Sitemap</h3>

    <ul>
      <li>
        <a href="<%= Routes.home_path(@conn, :index) %>">
          <span class="text-blue">William Penniman Storck</span>
        </a>
      </li>
      <li>
        <a href="<%= Routes.portfolio_path(@conn, :index) %>">
          <span class="text-blue">Portfolio:</span>
        </a>
        <ul>
          <%= for painting <- @paintings do %>
            <li>
              <a href="<%= Routes.paintings_path(@conn, :show, painting.slug) %>">
                <span class="text-blue">
                  <%= painting.name %>
                </span>
              </a>
            </li>
          <% end %>
        </ul>
      </li>
      <li>
        <a href="<%= Routes.contact_path(@conn, :index) %>">
          <span class="text-blue">Contact</span>
        </a>
      </li>
      <li>
        <a href="<%= Routes.privacy_path(@conn, :index) %>">
          <span class="text-blue">Privacy Policy</span>
        </a>
      </li>
    </ul>

  </div>

</div>

<%= render WilliamStorckPhxWeb.SharedView, "footer.html", assigns %>