lib/william_storck_phx_web/router.ex
defmodule WilliamStorckPhxWeb.Router do
  use WilliamStorckPhxWeb, :router

  alias WilliamStorckPhxWeb.Plugs.{RequireLogin, Authenticate}

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Authenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Must be logged out
  scope "/admin", WilliamStorckPhxWeb.Admin, as: :admin do
    pipe_through [:browser]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  # Must be logged in
  scope "/admin", WilliamStorckPhxWeb.Admin, as: :admin do
    pipe_through [:browser, RequireLogin]

    delete "/login", SessionController, :delete

    get "/", LandingController, :index
    resources "/users", UserController
    resources "/paintings", PaintingController
    resources "/categories", CategoryController
  end

  scope "/", WilliamStorckPhxWeb do
    pipe_through :browser # Use the default browser stack

    get "/", HomeController, :index

    get "/portfolio", PortfolioController, :index

    resources "/categories", CategoryController, only: [:show]

    resources "/paintings", PaintingsController, only: [:show]

    get "/contact", ContactController, :index
    post "/contact", ContactController, :capture_email

    get "/sitemap", SitemapController, :index
    get "/privacy", PrivacyController, :index


    get "/*path", PaintingsController, :index
  end
end

lib/william_storck_phx_web/views/admin/shared_view.ex
defmodule WilliamStorckPhxWeb.Admin.SharedView do
  use WilliamStorckPhxWeb, :view
end

lib/william_storck_phx_web/views/shared_view.ex
defmodule WilliamStorckPhxWeb.SharedView do
  use WilliamStorckPhxWeb, :view
end

lib/william_storck_phx_web/templates/shared/footer.html.eex
<div
  id="footer"
  class="container-fluid px-4 py-2 border-top border-secondary"
>
  <div class="d-md-none d-flex flex-column align-items-center justify-content-center">
    <div class="d-flex flex-row align-items-center justify-content-around my-2">
      <a href="<%= Routes.contact_path(@conn, :index) %>">Contact Us</a>

      <span class="mx-2">|</span>

      <a href="<%= Routes.privacy_path(@conn, :index) %>">Privacy Policy</a>

      <span class="mx-2">|</span>

      <a href="<%= Routes.sitemap_path(@conn, :index) %>">Sitemap</a>
    </div>

    <div class="my-2">
      <a
        href="https://instagram.com/wpstorck"
        class="text-secondary"
      >
        <i class="fab fa-instagram"></i>
      </a>
    </div>

    <p>
      <i class="far fa-copyright"></i>
      <%= DateTime.utc_now.year %>
      William Penniman Storck
    </p>
  </div>

  <div class="d-none d-md-flex align-items-center justify-content-between">
    <p class="mb-0">
      <i class="far fa-copyright"></i>
      <%= DateTime.utc_now.year %>
      William Penniman Storck
    </p>

    <a href="https://instagram.com/wpstorck" class="text-secondary">
      <i class="fab fa-instagram"></i>
    </a>

    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a href="<%= Routes.privacy_path(@conn, :index) %>" class="nav-link">
          Privacy Policy
        </a>
      </li>
      <li class="nav-item">
        <a href="<%= Routes.sitemap_path(@conn, :index) %>" class="nav-link">
          Sitemap
        </a>
      </li>
      <li class="nav-item">
        <a href="<%= Routes.contact_path(@conn, :index) %>" class="nav-link">
          Contact
        </a>
      </li>
    </ul>
  </div>
</div>

lib/william_storck_phx_web/templates/shared/navbar_clear.html.eex
<div
  id="navbar"
  class="navbar navbar-expand-lg fixed-top navbar-clear"
>
  <a
    href="<%= Routes.home_path(@conn, :index) %>"
    class="navbar-brand"
  >
    <h4 class="d-md-none heading-text text-white text-shadow mb-0">
      William Storck
    </h4>

    <h1 class="d-none d-md-block display-4 heading-text text-primary text-shadow">
      William Penniman Storck
    </h1>
  </a>

  <button
    type="button"
    data-toggle="collapse"
    data-target="#navbar-menu"
    class="navbar-toggler"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div
    id="navbar-menu"
    class="collapse navbar-collapse"
  >
    <ul class="navbar-nav ml-auto align-items-end mr-lg-4">
      <li class="nav-item mr-lg-4">
        <a
          href="<%= Routes.portfolio_path(@conn, :index) %>"
          class="nav-link"
        >
          <span class="text-white text-shadow">
            Portfolio
          </span>
        </a>
      </li>

      <li class="nav-item mr-lg-4">
        <a
          href="https://www.hsprints.com/william-storck"
          target="_blank"
          class="nav-link"
        >
          <span class="text-white text-shadow">
            Prints
          </span>
        </a>
      </li>

      <li class="nav-item">
        <a
          href="<%= Routes.contact_path(@conn, :index) %>"
          class="nav-link"
        >
          <span class="text-white text-shadow">
            Contact
          </span>
        </a>
      </li>
    </ul>
  </div>
</div>

lib/william_storck_phx_web/templates/shared/navbar_default.html.eex
<div
  id="navbar"
  class="navbar navbar-expand-lg fixed-top navbar-light border-bottom border-secondary"
>
  <a
    href="<%= Routes.home_path(@conn, :index) %>"
    class="navbar-brand"
  >
    <h4 class="d-md-none heading-text text-primary mb-0">
      WS
    </h4>

    <h1 class="d-none d-md-block display-4 heading-text text-primary">
      William Penniman Storck
    </h1>
  </a>

  <button
    type="button"
    data-toggle="collapse"
    data-target="#navbar-menu"
    class="navbar-toggler"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div
    id="navbar-menu"
    class="collapse navbar-collapse"
  >
    <ul class="navbar-nav ml-auto align-items-start">
      <li class="nav-item my-2 mr-lg-4">
        <a
          href="<%= Routes.home_path(@conn, :index) %>"
          class="nav-link"
        >
          <h4 class="d-lg-none text-black">
            Home
          </h4>
          <span class="d-none d-lg-inline-block text-black">
            Home
          </span>
        </a>
      </li>

      <li class="nav-item my-2 mr-lg-4">
        <a
          href="<%= Routes.portfolio_path(@conn, :index) %>"
          class="nav-link"
        >
          <h4 class="d-lg-none text-black">
            Portfolio
          </h4>
          <span class="d-none d-lg-inline-block text-black">
            Portfolio
          </span>
        </a>
      </li>

      <li class="nav-item my-2 mr-lg-4">
        <a
          href="<%= Routes.contact_path(@conn, :index) %>"
          class="nav-link"
        >
          <h4 class="d-lg-none text-black">
            Contact
          </h4>
          <span class="d-none d-lg-inline-block text-black">
            Contact
          </span>
        </a>
      </li>
    </ul>
  </div>
</div>

lib/william_storck_phx_web/templates/shared/navbar_min.html.eex
<div
  id="navbar"
  class="navbar fixed-top navbar-min"
>
  <a
    href="<%= Routes.home_path(@conn, :index) %>"
    class="navbar-brand"
  >
    <h4 class="heading-text text-primary mb-0">
      WS
    </h4>
  </a>

  <button
    type="button"
    data-toggle="collapse"
    data-target="#navbar-menu"
    class="navbar-toggler"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div
    id="navbar-menu"
    class="collapse navbar-collapse"
  >
    <ul class="navbar-nav ml-auto align-items-end">
      <li class="nav-item my-2 mr-3">
        <a
          href="<%= Routes.home_path(@conn, :index) %>"
          class="nav-link"
        >
          <span class="text-black">
            Home
          </span>
        </a>
      </li>

      <li class="nav-item my-2 mr-3">
        <a
          href="<%= Routes.portfolio_path(@conn, :index) %>"
          class="nav-link"
        >
          <span class="text-black">
            Portfolio
          </span>
        </a>
      </li>

      <li class="nav-item my-2 mr-3">
        <a
          href="https://www.hsprints.com/william-storck"
          target="_blank"
          class="nav-lnk"
        >
          <span class="text-black">
            Prints
          </span>
        </a>
      </li>

      <li class="nav-item my-2 mr-3">
        <a
          href="<%= Routes.contact_path(@conn, :index) %>"
          class="nav-link"
        >
          <span class="text-black">
            Contact
          </span>
        </a>
      </li>
    </ul>
  </div>
</div>